reviewers:
  # The default core reviewers.
  # Reviews may only be requested from collaborators.
  defaults:
    - AndreySkripachev
    - khoanguyen-saritasa
    - maxineo
    - viktor-sakhno-saritasa
    - pavelzadorin-saritasa
    
