reviewers:
  # The default core reviewers.
  # Reviews may only be requested from collaborators.
  defaults:
    - panov-aleksey-saritasa
    - ShestakovaElena
    - dbitkovski
    - DaniilMaslovSaritasa
